apiVersion: v1
kind: Pod
metadata:
  name: nginx-01
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: www-volume
      mountPath: /usr/share/nginx/html

  volumes:
  - name: www-volume
    hostPath:
      # directoy location on host
      path: /www
      # this field is optional
      type: Directory

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-02
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: www-volume
      mountPath: /usr/share/nginx/html

  volumes:
  - name: www-volume
    hostPath:
      # directory location on host
      path: /www
      # this field is optional
      type: Directory
