apiVersion: v1
kind: Pod
metadata:
  name: nginx-04
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: index
      mountPath: /usr/share/nginx/html

  volumes:
    - name: index
      configMap:
        name: index-html
        items:
          - key: index.html
            path: index.html
