apiVersion: v1
kind: Secret
metadata:
  name: tlstest-secret
  namespace: testing
type: kubernetes.io/tls
data:
  tls.crt: REPLACE_WITH_CERT
  tls.key: REPLACE_WITH_KEY

# Generate cert and key by following:
# $ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${KEY_FILE} -out ${CERT_FILE} -subj "/CN=${HOST}/O=${HOST}" -addext "subjectAltName = DNS:${HOST}"
# https://kubernetes.github.io/ingress-nginx/user-guide/tls/
#
# Key and CERT FILE need to be placed in this files in base64 encoding.
# Execute:
#
# For CERT File:
# sed -i "0,/REPLACE_WITH_CERT/s//`cat tls.crt|base64 -w0`/" 01.1-default-server-secret.yaml
#
# For Key File:
# sed -i "0,/REPLACE_WITH_KEY/s//`cat tls.key|base64 -w0`/" 01.1-default-server-secret.yaml
