apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: thanos
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: thanos-sidecar-service
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.41.0
  name: thanos-sidecar-service
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: grpc
    port: 10901
    targetPort: 10901
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus