apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-env-resources
  namespace: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      role: nginx-env
  template:
    metadata:
      labels:
        role: nginx-env
    spec:
      containers:
      - name: nginx-env-resources
        image: nginx
        imagePullPolicy: IfNotPresent
        #command: ["/bin/sh"] 
        #args: ["-c", "echo $MYSQL_ROOT_PASSWORD"] # kubectl logs [pod]      
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
