apiVersion: v1
kind: ConfigMap
metadata:
  name: my-loadtest-locustfile
data:
  main.py: |-
    from locust import HttpUser, task, between

    class MyUser(HttpUser):
        wait_time = between(5, 9)

        @task(4)
        def index(self):
            self.client.get("/")
