apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello
  minReplicas: 3
  maxReplicas: 10
  metrics:
  # Metrics "Pods" takes the metric average
  # for all of the pods controlled by the hpa deployment.
  - type: Pods
    pods:
      metric:
        name: request-per-second
      target:
        type: AverageValue
        averageValue: 1k
  # Not tested, still investigating how to use it.