apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  minReadySeconds: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:3.4.1
          command:
            - mongod
            - --replSet
            - rs0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: web
              protocol: TCP
        - name: init-mongo
          image: mongo:3.4.1
          command:
            - bash
            - /config/init.sh
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /config
            - name: persistent
              mountPath: /data/db
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: mongo-init
          name: config
  volumeClaimTemplates:
  - metadata:
      name: persistent
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: # REPLACE_WITH_CUSTOM_SC
      resources:
        requests:
          storage: 1Gi
