apiVersion: v1
kind: Service
metadata:
 name: hello
 namespace: testing
 labels:
   role: hello
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 8080
    targetPort: 8080
  selector:
    role: hello
