apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hello.pereirajean.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: hello-v1-svc
            port:
              number: 80