apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-cloud-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: [REPLACE_WITH_CLOUDPROVIDER_SC]
