apiVersion: v1
kind: Pod
metadata:
  name: nginx-cloud-01
  labels:
    app: nginx-cloud
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: www-volume
      mountPath: /usr/share/nginx/html

  volumes:
  - name: www-volume
    persistentVolumeClaim:
      claimName: nginx-cloud-pvc
