apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: testing
  labels:
    role: php-apache
spec:
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    role: php-apache
