apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  containers:
  - name: master
    image: redis
    env:
      - name: MASTER
        value: "true"
    ports:
      - containerPort: 6379
    resources:
      limits:
        cpu: "100m"
        memory: "256Mi"