apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: "Reconcile"
    kubernetes.io/name: "Alertmanager"
    addonmanager.kubernetes.io/mode: "EnsureExists"
spec:
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    k8s-app: "alertmanager"
  type: "ClusterIP"
