apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort
  ports:
  - name: https # http
    protocol: TCP
    port: 443 #80
    targetPort: 443 #80
    nodePort: 30000
  selector:
    app: nginx-ingress
    

