apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: developer-user
spec: # Replace request wit csr file content.
  request: MIICUjCCAToCAQAwDTELMAkGA1UEBhMCQ1IwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTDw9gzSuJgJk76iiDhaEiIvOWaPWocB0Oy50IljzntBywNf8xvqghAIvLUgMinE5aJJ7bjoSjWwIOoYXWDKCr6MWq1Sk5xcBkNdGYaWJ8wk9q4vnk5DFKPnwBy/JPxejwoeZ/bglfRa2IOzV/zJLG7Ds1CQBxiGWCoDD6HfWWbrwq7o7XP3Hm3/vxWQkU0ORLC+buWYdUxKZbVXjYeJQbsee9kPQRxtOief/3GyC6l08LqUinqotfowGgAhRveOysRDtj526xLFvKg7Q4fJvb1IHboJNMeO3ECdN1iK9mPiB66rkrrYaJS4mFJMLHFVpWPBrcnf2mnq5jRAZiwvFFAgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAQEASMC6F31PxxjCJbsgtezOCJPk4K0Q4v/Kyg391l6fzYC2cGi4wUPk07B+r+DO0W/DxWhAF3le/xp4YUQQXEkjWt+QCMFrbUSVSVYTL2Oxtu64uTL/av4VQ5eAH+Ongrxwt64Xli55l6dimvcSLFPpFXVcqiF1KqNpOMgxgS83UPiwcauRECrPu0nZRdI41zPPYlOS0lmvgPOBLQYooWOSqBHqDTaI+uiq6j3CgphFFhf6oCCzrPANQynZKu8VqJM7Z3LmHAVh6QZI909YOXZ9qLqoKVxhnsT6+bd+BMRRzBt19e1+kFVNdvs674J0n06Lo0ByBWcrzf2vh17hV/EvqQ==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # one day
  usages:
  - client auth