apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: development
subjects:
- kind: User
  name: developer-user
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""