apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cluster-role
  name: cluster-role
  namespace: development

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dashboard-cluster-role
  name: cluster-role
rules:
- apiGroups: 
  - ""
  - extentions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: dashboard-cluster-role-binding
  name: reader-pod-admin
subjects:
- kind: ServiceAccount
  name: cluster-role
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role

---
apiVersion: v1
kind: Pod
metadata:
  name: dashboard-cluster-role-pod
  namespace: development
spec:
  serviceAccountName: cluster-role
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/bash", "-c", "curl https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/apis/apps/v1
  --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  --header \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"  && sleep 999"]