apiVersion: v1
kind: Service
metadata:
  name: hello-deploy
  namespace: testing
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008
  selector:
    role: hello-deploy
