kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runner-gitlab-runner-deployments
roleRef:
  kind: ClusterRole
  name: "deployment-manager"
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    namespace: "gitlab-runner"
    name: "default"
    apiGroup: ""
    