apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "This priority class should be used for for high prioritie service pods only"

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-nonpreemptive
value: 1000000
preemptionPolicy: Never
globalDefault: false
description: "This priority class should be used for high-priority service pods only with no preemption"

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 500000
globalDefault: true # This will be the default PriorityClass for new pods, only one can be set at a time.
description: "This priority class should be used for low-priority service pods only"