apiVersion: v1
kind: Pod
metadata:
  name: nginx-lp
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "1200m"
  priorityClassName: low-priority
