apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: testing
  labels:
    role: wordpress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    role: wordpress
