apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: testing
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 30002
  selector:
    app: nginx
